[package]
name = "scripts"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "dylib"]

[dependencies]
bevy = { version = "0.10.1", features = ["bevy_dynamic_plugin"] }

[features]
default = []
dynamic = ["bevy/bevy_dynamic_plugin"]